'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

type DemoPhase =
  | 'idle'
  | 'alert'
  | 'investigating'
  | 'discovering'
  | 'writing_code'
  | 'awaiting_approval'
  | 'deploying'
  | 'executing'
  | 'monitoring'
  | 'resolved'

interface Runner {
  id: string
  name: string
  platform: string
  status: 'idle' | 'receiving' | 'executing' | 'done'
}

const RUNNERS: Runner[] = [
  { id: 'r1', name: 'prod-k8s-01', platform: 'Kubernetes', status: 'idle' },
  { id: 'r2', name: 'prod-k8s-02', platform: 'Kubernetes', status: 'idle' },
  { id: 'r3', name: 'aws-lambda-prod', platform: 'AWS Lambda', status: 'idle' },
  { id: 'r4', name: 'edge-cloudflare', platform: 'Cloudflare', status: 'idle' },
]

const DISCOVERY_STEPS = [
  { source: 'Prometheus', finding: 'memory_usage > 2GB on payment-svc' },
  { source: 'Git History', finding: 'Recent commit: "Add session caching" (a7ef82d)' },
  { source: 'Source Code', finding: 'PaymentProcessor.java uses unbounded HashMap' },
  { source: 'Kubernetes', finding: '3 pods affected across 2 namespaces' },
  { source: 'Datadog', finding: 'Error rate spike correlates with deploy time' },
]

const CODE_CONTENT = `// fix-memory-leak.patch
// Generated by Knot0 Agent

--- a/src/main/java/com/acme/payment/PaymentProcessor.java
+++ b/src/main/java/com/acme/payment/PaymentProcessor.java
@@ -12,7 +12,15 @@ import java.util.Map;
+import java.util.LinkedHashMap;

 public class PaymentProcessor {
-    private Map<String, Session> cache = new HashMap<>();
+    private static final int MAX_CACHE = 1000;
+
+    private Map<String, Session> cache = new LinkedHashMap<>(
+        MAX_CACHE, 0.75f, true
+    ) {
+        @Override
+        protected boolean removeEldestEntry(Entry<String, Session> e) {
+            return size() > MAX_CACHE;
+        }
+    };

     public PaymentResult process(PaymentRequest req) {`

export function FullDemo() {
  const [phase, setPhase] = useState<DemoPhase>('idle')
  const [visibleDiscoveries, setVisibleDiscoveries] = useState(0)
  const [visibleCodeChars, setVisibleCodeChars] = useState(0)
  const [runners, setRunners] = useState(RUNNERS)
  const [executionProgress, setExecutionProgress] = useState(0)
  const [hasInteracted, setHasInteracted] = useState(false)
  const timeoutRef = useRef<NodeJS.Timeout | null>(null)

  const clearTimeouts = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
      timeoutRef.current = null
    }
  }

  const resetDemo = useCallback(() => {
    clearTimeouts()
    setPhase('idle')
    setVisibleDiscoveries(0)
    setVisibleCodeChars(0)
    setRunners(RUNNERS)
    setExecutionProgress(0)
    setHasInteracted(false)
  }, [])

  const startDemo = useCallback(() => {
    resetDemo()
    setTimeout(() => setPhase('alert'), 100)
  }, [resetDemo])

  const handleApprove = useCallback(() => {
    setHasInteracted(true)
    clearTimeouts()
    setPhase('deploying')
  }, [])

  const handleDeny = useCallback(() => {
    setHasInteracted(true)
    clearTimeouts()
    resetDemo()
  }, [resetDemo])

  // Auto-start demo on mount
  useEffect(() => {
    const timer = setTimeout(startDemo, 1000)
    return () => clearTimeout(timer)
  }, [startDemo])

  // Phase progression
  useEffect(() => {
    clearTimeouts()

    switch (phase) {
      case 'alert':
        timeoutRef.current = setTimeout(() => setPhase('investigating'), 2000)
        break

      case 'investigating':
        timeoutRef.current = setTimeout(() => setPhase('discovering'), 1500)
        break

      case 'discovering':
        if (visibleDiscoveries < DISCOVERY_STEPS.length) {
          timeoutRef.current = setTimeout(() => {
            setVisibleDiscoveries(prev => prev + 1)
          }, 800)
        } else {
          timeoutRef.current = setTimeout(() => setPhase('writing_code'), 500)
        }
        break

      case 'writing_code':
        if (visibleCodeChars < CODE_CONTENT.length) {
          const char = CODE_CONTENT[visibleCodeChars]
          const delay = char === '\n' ? 30 : char === ' ' ? 8 : 12
          timeoutRef.current = setTimeout(() => {
            setVisibleCodeChars(prev => prev + 1)
          }, delay)
        } else {
          timeoutRef.current = setTimeout(() => setPhase('awaiting_approval'), 500)
        }
        break

      case 'awaiting_approval':
        // Auto-approve after 10 seconds if no interaction
        timeoutRef.current = setTimeout(() => {
          if (!hasInteracted) {
            handleApprove()
          }
        }, 10000)
        break

      case 'deploying':
        // Animate runners receiving the deployment
        let runnerIndex = 0
        const deployInterval = setInterval(() => {
          if (runnerIndex < RUNNERS.length) {
            setRunners(prev => prev.map((r, i) =>
              i === runnerIndex ? { ...r, status: 'receiving' } : r
            ))
            runnerIndex++
          } else {
            clearInterval(deployInterval)
            setTimeout(() => setPhase('executing'), 500)
          }
        }, 300)
        return () => clearInterval(deployInterval)

      case 'executing':
        // Progress bar and runner status updates
        const execInterval = setInterval(() => {
          setExecutionProgress(prev => {
            if (prev >= 100) {
              clearInterval(execInterval)
              setTimeout(() => setPhase('monitoring'), 500)
              return 100
            }
            // Update runner statuses as we progress
            if (prev === 25) {
              setRunners(r => r.map((runner, i) => i === 0 ? { ...runner, status: 'executing' } : runner))
            } else if (prev === 50) {
              setRunners(r => r.map((runner, i) => i <= 1 ? { ...runner, status: i === 0 ? 'done' : 'executing' } : runner))
            } else if (prev === 75) {
              setRunners(r => r.map((runner, i) => i <= 2 ? { ...runner, status: i <= 1 ? 'done' : 'executing' } : runner))
            } else if (prev === 95) {
              setRunners(r => r.map(runner => ({ ...runner, status: 'done' })))
            }
            return prev + 5
          })
        }, 150)
        return () => clearInterval(execInterval)

      case 'monitoring':
        timeoutRef.current = setTimeout(() => setPhase('resolved'), 2000)
        break

      case 'resolved':
        // Restart demo after showing success
        timeoutRef.current = setTimeout(() => {
          resetDemo()
          setTimeout(startDemo, 1000)
        }, 4000)
        break
    }

    return clearTimeouts
  }, [phase, visibleDiscoveries, visibleCodeChars, hasInteracted, handleApprove, resetDemo, startDemo])

  return (
    <div className="min-h-[calc(100vh-3.5rem)] flex flex-col">
      {/* Status Bar */}
      <div className="border-b border-black-border bg-black-light px-4 py-2">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <span className="text-amber font-mono text-sm font-medium">CONTROL ROOM</span>
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
              <span className="text-white-dim text-xs font-mono">LIVE DEMO</span>
            </div>
          </div>
          <div className="flex items-center gap-6 text-xs font-mono text-white-muted">
            <span>● 1 AGENT</span>
            <span>● {RUNNERS.length} RUNNERS</span>
            <button
              onClick={startDemo}
              className="text-amber hover:text-amber/80 transition-colors"
            >
              [RESTART]
            </button>
          </div>
        </div>
      </div>

      {/* Main Demo Area */}
      <div className="flex-1 flex">
        {/* Left: Activity Feed */}
        <div className="w-1/2 border-r border-black-border p-6 overflow-hidden">
          <div className="text-white-muted text-xs font-mono mb-4">AGENT ACTIVITY</div>

          <div className="space-y-3 font-mono text-sm">
            {/* Idle state */}
            <AnimatePresence>
              {phase === 'idle' && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="text-white-dim"
                >
                  Waiting for incidents...
                </motion.div>
              )}
            </AnimatePresence>

            {/* Alert */}
            <AnimatePresence>
              {phase !== 'idle' && (
                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="flex items-start gap-3"
                >
                  <span className="text-red-500">●</span>
                  <div>
                    <div className="text-red-500 font-medium">ALERT: payment-svc memory leak</div>
                    <div className="text-white-muted text-xs">Production • High severity • Auto-detected</div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Investigating */}
            <AnimatePresence>
              {['investigating', 'discovering', 'writing_code', 'awaiting_approval', 'deploying', 'executing', 'monitoring', 'resolved'].includes(phase) && (
                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="flex items-start gap-3"
                >
                  <span className="text-cyan">◐</span>
                  <div className="text-cyan">Agent investigating...</div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Discovery Steps */}
            <AnimatePresence>
              {DISCOVERY_STEPS.slice(0, visibleDiscoveries).map((step, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="flex items-start gap-3 pl-6"
                >
                  <span className="text-white-muted">→</span>
                  <div>
                    <span className="text-amber">[{step.source}]</span>
                    <span className="text-white ml-2">{step.finding}</span>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>

            {/* Writing code indicator */}
            <AnimatePresence>
              {['writing_code', 'awaiting_approval', 'deploying', 'executing', 'monitoring', 'resolved'].includes(phase) && (
                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="flex items-start gap-3"
                >
                  <span className="text-cyan">✎</span>
                  <div className="text-cyan">Synthesizing fix...</div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Deploying */}
            <AnimatePresence>
              {['deploying', 'executing', 'monitoring', 'resolved'].includes(phase) && (
                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="flex items-start gap-3"
                >
                  <span className="text-amber">▶</span>
                  <div className="text-amber">Human approved. Deploying to {RUNNERS.length} runners...</div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Resolved */}
            <AnimatePresence>
              {phase === 'resolved' && (
                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="flex items-start gap-3"
                >
                  <span className="text-green-500">✓</span>
                  <div className="text-green-500 font-medium">RESOLVED - All services healthy</div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>

        {/* Right: Code & Runners */}
        <div className="w-1/2 flex flex-col">
          {/* Code Panel */}
          <div className="flex-1 p-6 border-b border-black-border overflow-hidden">
            <div className="text-white-muted text-xs font-mono mb-4 flex items-center justify-between">
              <span>CODE OUTPUT</span>
              {visibleCodeChars > 0 && (
                <span className="text-amber">fix-memory-leak.patch</span>
              )}
            </div>
            <div className="bg-black-light rounded border border-black-border p-4 font-mono text-xs h-64 overflow-hidden">
              <pre className="text-white whitespace-pre-wrap">
                {CODE_CONTENT.slice(0, visibleCodeChars)}
                {phase === 'writing_code' && (
                  <span className="inline-block w-2 h-4 bg-amber animate-pulse" />
                )}
              </pre>
            </div>
          </div>

          {/* Runners Panel */}
          <div className="p-6">
            <div className="text-white-muted text-xs font-mono mb-4">RUNNERS</div>
            <div className="grid grid-cols-2 gap-3">
              {runners.map((runner) => (
                <motion.div
                  key={runner.id}
                  className={`
                    border rounded p-3 font-mono text-xs transition-colors
                    ${runner.status === 'idle' ? 'border-black-border text-white-dim' : ''}
                    ${runner.status === 'receiving' ? 'border-amber bg-amber/5 text-amber' : ''}
                    ${runner.status === 'executing' ? 'border-cyan bg-cyan/5 text-cyan' : ''}
                    ${runner.status === 'done' ? 'border-green-500 bg-green-500/5 text-green-500' : ''}
                  `}
                  animate={runner.status === 'executing' ? { opacity: [1, 0.7, 1] } : {}}
                  transition={{ repeat: Infinity, duration: 0.5 }}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-medium">{runner.name}</span>
                    <span className={`w-2 h-2 rounded-full ${
                      runner.status === 'idle' ? 'bg-white-muted' :
                      runner.status === 'receiving' ? 'bg-amber' :
                      runner.status === 'executing' ? 'bg-cyan animate-pulse' :
                      'bg-green-500'
                    }`} />
                  </div>
                  <div className="text-white-muted">{runner.platform}</div>
                </motion.div>
              ))}
            </div>

            {/* Execution Progress */}
            <AnimatePresence>
              {(phase === 'executing' || phase === 'monitoring' || phase === 'resolved') && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="mt-4"
                >
                  <div className="flex items-center justify-between text-xs font-mono mb-2">
                    <span className="text-white-muted">Deployment Progress</span>
                    <span className="text-cyan">{executionProgress}%</span>
                  </div>
                  <div className="h-1 bg-black-border rounded-full overflow-hidden">
                    <motion.div
                      className="h-full bg-cyan"
                      initial={{ width: 0 }}
                      animate={{ width: `${executionProgress}%` }}
                    />
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

      {/* Approval Bar */}
      <AnimatePresence>
        {phase === 'awaiting_approval' && (
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 50 }}
            className="border-t border-black-border bg-black-light p-6"
          >
            <div className="max-w-4xl mx-auto">
              <div className="flex flex-col md:flex-row items-center justify-between gap-4">
                <div className="font-mono text-sm">
                  <div className="text-white mb-1">Ready to deploy fix-memory-leak.patch</div>
                  <div className="text-white-muted text-xs">
                    Target: payment-svc • Blast radius: <span className="text-amber">MEDIUM</span> •
                    Affected: 4 services • Rollback: Automatic
                  </div>
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={handleApprove}
                    className="px-8 py-3 bg-amber text-black font-mono text-sm font-medium rounded hover:bg-amber/90 transition-colors animate-pulse"
                  >
                    APPROVE
                  </button>
                  <button
                    onClick={handleDeny}
                    className="px-8 py-3 border border-white-muted text-white font-mono text-sm rounded hover:bg-white/5 transition-colors"
                  >
                    DENY
                  </button>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Success Banner */}
      <AnimatePresence>
        {phase === 'resolved' && (
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 50 }}
            className="border-t border-green-500/30 bg-green-500/10 p-6"
          >
            <div className="max-w-4xl mx-auto text-center font-mono">
              <div className="text-green-500 text-lg font-medium mb-2">
                ✓ Incident Resolved
              </div>
              <div className="text-white-dim text-sm">
                Memory leak fixed across 4 services in 12 seconds. Zero downtime.
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
