'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

type IncidentState =
  | 'investigating'
  | 'writing_code'
  | 'awaiting_approval'
  | 'executing'
  | 'resolved'
  | 'denied'

interface Incident {
  id: string
  title: string
  severity: 'high' | 'medium' | 'low'
  agentSteps: { time: string; text: string }[]
  code: {
    filename: string
    language: string
    content: string
  }
  approval: {
    target: string
    blastRadius: 'HIGH' | 'MEDIUM' | 'LOW'
    affected: string[]
    rollback: string
  }
}

const INCIDENTS: Incident[] = [
  {
    id: 'memory-leak',
    title: 'payment-svc memory leak detected',
    severity: 'high',
    agentSteps: [
      { time: '14:32:01', text: 'Querying Prometheus metrics...' },
      { time: '14:32:02', text: 'memory_usage_bytes > 2GB threshold' },
      { time: '14:32:03', text: 'Correlating with recent deploys...' },
      { time: '14:32:04', text: 'Found: commit a7ef82d "Add session caching"' },
      { time: '14:32:05', text: 'Analyzing PaymentProcessor.java...' },
      { time: '14:32:06', text: 'Root cause: unbounded HashMap growth' },
      { time: '14:32:08', text: 'Synthesizing fix...' },
    ],
    code: {
      filename: 'fix-memory-leak.patch',
      language: 'java',
      content: `--- a/src/main/java/com/knot0/payment/PaymentProcessor.java
+++ b/src/main/java/com/knot0/payment/PaymentProcessor.java
@@ -12,6 +12,7 @@ import java.util.HashMap;
 import java.util.Map;
+import java.util.LinkedHashMap;

 public class PaymentProcessor {

-    private Map<String, Session> sessionCache = new HashMap<>();
+    private static final int MAX_CACHE_SIZE = 1000;
+
+    private Map<String, Session> sessionCache = new LinkedHashMap<>(
+        MAX_CACHE_SIZE, 0.75f, true
+    ) {
+        @Override
+        protected boolean removeEldestEntry(Map.Entry<String, Session> eldest) {
+            return size() > MAX_CACHE_SIZE;
+        }
+    };`,
    },
    approval: {
      target: 'payment-svc (prod-cluster-01)',
      blastRadius: 'MEDIUM',
      affected: ['payment-svc', 'checkout-svc', 'billing-svc', 'analytics-svc'],
      rollback: 'Automatic if health check fails within 60s',
    },
  },
  {
    id: 'oom-remediation',
    title: 'checkout-svc high error rate',
    severity: 'high',
    agentSteps: [
      { time: '14:35:01', text: 'Alert: checkout-svc error_rate > 5%' },
      { time: '14:35:02', text: 'Querying logs for error patterns...' },
      { time: '14:35:04', text: 'Found: ConnectionTimeout to inventory-svc' },
      { time: '14:35:05', text: 'Checking inventory-svc health...' },
      { time: '14:35:06', text: 'inventory-svc: 2/5 pods CrashLoopBackOff' },
      { time: '14:35:08', text: 'Analyzing pod events...' },
      { time: '14:35:09', text: 'OOMKilled - memory limit exceeded' },
      { time: '14:35:11', text: 'Writing remediation script...' },
    ],
    code: {
      filename: 'remediate-inventory-oom.sh',
      language: 'bash',
      content: `#!/bin/bash
# remediate-inventory-oom.sh
# Generated by Knot0 Agent

set -euo pipefail

DEPLOYMENT="inventory-svc"
NAMESPACE="production"
NEW_MEMORY_LIMIT="1024Mi"

echo "[knot0] Patching $DEPLOYMENT memory limits..."

kubectl patch deployment "$DEPLOYMENT" -n "$NAMESPACE" --type=json -p='[
  {
    "op": "replace",
    "path": "/spec/template/spec/containers/0/resources/limits/memory",
    "value": "'"$NEW_MEMORY_LIMIT"'"
  }
]'

echo "[knot0] Waiting for rollout..."
kubectl rollout status deployment/"$DEPLOYMENT" -n "$NAMESPACE" --timeout=120s

echo "[knot0] ✓ Remediation successful"`,
    },
    approval: {
      target: 'inventory-svc (prod-cluster-01)',
      blastRadius: 'HIGH',
      affected: ['inventory-svc', 'checkout-svc', 'order-svc', 'analytics-svc', 'reporting-svc'],
      rollback: 'Automatic rollback if pods fail to start within 120s',
    },
  },
  {
    id: 'backup-automation',
    title: 'Configure nightly database backup',
    severity: 'low',
    agentSteps: [
      { time: '14:40:01', text: 'Processing: "backup prod database nightly"' },
      { time: '14:40:02', text: 'Discovering database configuration...' },
      { time: '14:40:03', text: 'Found: PostgreSQL on rds-prod-01' },
      { time: '14:40:04', text: 'Checking existing backup schedules...' },
      { time: '14:40:05', text: 'No conflicts found' },
      { time: '14:40:07', text: 'Writing automation manifest...' },
    ],
    code: {
      filename: 'backup-automation.knot0.yml',
      language: 'yaml',
      content: `# backup-automation.knot0.yml
apiVersion: knot0.io/v1
kind: Automation
metadata:
  name: nightly-prod-backup
  namespace: production
spec:
  schedule: "0 2 * * *"  # 2 AM UTC daily

  steps:
    - name: create-snapshot
      runner: aws-prod-runner
      action: |
        aws rds create-db-snapshot \\
          --db-instance-identifier rds-prod-01 \\
          --db-snapshot-identifier "prod-backup-$(date +%Y%m%d)"
      timeout: 30m

    - name: notify-slack
      runner: internal-runner
      action: |
        curl -X POST "$SLACK_WEBHOOK_OPS" \\
          -d '{"text": "✓ Nightly backup completed"}'`,
    },
    approval: {
      target: 'rds-prod-01',
      blastRadius: 'LOW',
      affected: ['rds-prod-01'],
      rollback: 'Schedule can be disabled via kubectl delete',
    },
  },
]

export function MissionFeed() {
  const [currentIncidentIndex, setCurrentIncidentIndex] = useState(0)
  const [state, setState] = useState<IncidentState>('investigating')
  const [visibleSteps, setVisibleSteps] = useState(0)
  const [visibleCodeChars, setVisibleCodeChars] = useState(0)
  const [isAutoPlaying, setIsAutoPlaying] = useState(true)
  const timeoutRef = useRef<NodeJS.Timeout | null>(null)

  const incident = INCIDENTS[currentIncidentIndex]

  const clearTimeouts = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
      timeoutRef.current = null
    }
  }

  const advanceToNextIncident = useCallback(() => {
    setCurrentIncidentIndex((prev) => (prev + 1) % INCIDENTS.length)
    setState('investigating')
    setVisibleSteps(0)
    setVisibleCodeChars(0)
  }, [])

  const handleApprove = useCallback(() => {
    clearTimeouts()
    setState('executing')
    timeoutRef.current = setTimeout(() => {
      setState('resolved')
      timeoutRef.current = setTimeout(() => {
        advanceToNextIncident()
      }, 2000)
    }, 3000)
  }, [advanceToNextIncident])

  const handleDeny = useCallback(() => {
    clearTimeouts()
    setState('denied')
    timeoutRef.current = setTimeout(() => {
      advanceToNextIncident()
    }, 3000)
  }, [advanceToNextIncident])

  // Auto-advance through states
  useEffect(() => {
    if (!isAutoPlaying) return

    clearTimeouts()

    if (state === 'investigating') {
      if (visibleSteps < incident.agentSteps.length) {
        timeoutRef.current = setTimeout(() => {
          setVisibleSteps((prev) => prev + 1)
        }, 600)
      } else {
        timeoutRef.current = setTimeout(() => {
          setState('writing_code')
        }, 500)
      }
    } else if (state === 'writing_code') {
      if (visibleCodeChars < incident.code.content.length) {
        const char = incident.code.content[visibleCodeChars]
        const delay = char === '\n' ? 50 : char === ' ' ? 10 : 15
        timeoutRef.current = setTimeout(() => {
          setVisibleCodeChars((prev) => prev + 1)
        }, delay)
      } else {
        timeoutRef.current = setTimeout(() => {
          setState('awaiting_approval')
        }, 500)
      }
    } else if (state === 'awaiting_approval') {
      // Wait for user interaction, but auto-approve after 15 seconds
      timeoutRef.current = setTimeout(() => {
        handleApprove()
      }, 15000)
    }

    return clearTimeouts
  }, [state, visibleSteps, visibleCodeChars, incident, isAutoPlaying, handleApprove])

  const getSeverityColor = (severity: Incident['severity']) => {
    switch (severity) {
      case 'high': return 'text-red-500'
      case 'medium': return 'text-amber'
      case 'low': return 'text-cyan'
    }
  }

  const getBlastRadiusColor = (radius: 'HIGH' | 'MEDIUM' | 'LOW') => {
    switch (radius) {
      case 'HIGH': return 'text-red-500 bg-red-500/10'
      case 'MEDIUM': return 'text-amber bg-amber/10'
      case 'LOW': return 'text-cyan bg-cyan/10'
    }
  }

  return (
    <div className="w-full max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-black-border px-4 py-2 bg-black-light">
        <div className="flex items-center gap-3">
          <span className="text-amber font-mono text-sm">KNOT0 CONTROL ROOM</span>
          <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
          <span className="text-white-dim text-xs">LIVE</span>
        </div>
        <div className="flex items-center gap-4 text-xs text-white-muted font-mono">
          <span>● 3 AGENTS</span>
          <span>● 12 RUNNERS</span>
        </div>
      </div>

      {/* Active Incident */}
      <div className="border-x border-b border-black-border bg-black">
        <div className="flex items-center gap-3 px-4 py-2 border-b border-black-border">
          <span className="text-white-dim text-xs">▶ ACTIVE INCIDENT</span>
          <span className={`text-xs ${getSeverityColor(incident.severity)}`}>
            [{incident.severity.toUpperCase()}]
          </span>
          <span className="text-white text-sm font-mono">{incident.title}</span>
        </div>

        {/* Main content grid */}
        <div className="grid md:grid-cols-2 gap-0">
          {/* Left: Agent Activity */}
          <div className="border-r border-black-border p-4">
            <div className="text-white-muted text-xs mb-3 font-mono">AGENT ACTIVITY</div>
            <div className="space-y-1 font-mono text-sm min-h-[200px]">
              <AnimatePresence>
                {incident.agentSteps.slice(0, visibleSteps).map((step, i) => (
                  <motion.div
                    key={`${incident.id}-${i}`}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="flex gap-2"
                  >
                    <span className="text-white-muted">{step.time}</span>
                    <span className="text-white">{step.text}</span>
                  </motion.div>
                ))}
              </AnimatePresence>
              {state === 'investigating' && visibleSteps < incident.agentSteps.length && (
                <div className="flex gap-2 text-cyan animate-pulse">
                  <span className="text-white-muted">◐</span>
                  <span>processing...</span>
                </div>
              )}
              {state === 'writing_code' && (
                <div className="flex gap-2 text-cyan">
                  <span className="text-white-muted">◐</span>
                  <span className="animate-pulse">streaming code...</span>
                </div>
              )}
            </div>
          </div>

          {/* Right: Code Output */}
          <div className="p-4">
            <div className="text-white-muted text-xs mb-3 font-mono flex items-center gap-2">
              <span>CODE OUTPUT</span>
              {(state === 'writing_code' || state === 'awaiting_approval' || state === 'executing' || state === 'resolved') && (
                <span className="text-amber">— {incident.code.filename}</span>
              )}
            </div>
            <div className="bg-black-dark rounded border border-black-border p-3 font-mono text-xs min-h-[200px] overflow-hidden">
              <pre className="text-white whitespace-pre-wrap">
                {incident.code.content.slice(0, visibleCodeChars)}
                {state === 'writing_code' && (
                  <span className="inline-block w-2 h-4 bg-amber animate-pulse" />
                )}
              </pre>
            </div>
          </div>
        </div>

        {/* Approval Section */}
        <AnimatePresence>
          {(state === 'awaiting_approval' || state === 'executing' || state === 'resolved' || state === 'denied') && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="border-t border-black-border p-4"
            >
              {state === 'awaiting_approval' && (
                <div className="space-y-4">
                  <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm font-mono">
                    <div>
                      <span className="text-white-muted">Target: </span>
                      <span className="text-white">{incident.approval.target}</span>
                    </div>
                    <div>
                      <span className="text-white-muted">Blast radius: </span>
                      <span className={`px-2 py-0.5 rounded ${getBlastRadiusColor(incident.approval.blastRadius)}`}>
                        {incident.approval.blastRadius}
                      </span>
                    </div>
                    <div>
                      <span className="text-white-muted">Affected: </span>
                      <span className="text-white">{incident.approval.affected.length} services</span>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <button
                      onClick={handleApprove}
                      className="px-6 py-2 bg-amber text-black font-mono text-sm font-medium rounded hover:bg-amber/90 transition-colors animate-pulse"
                    >
                      APPROVE
                    </button>
                    <button
                      onClick={handleDeny}
                      className="px-6 py-2 border border-white-muted text-white font-mono text-sm rounded hover:bg-white/5 transition-colors"
                    >
                      DENY
                    </button>
                    <button
                      className="px-6 py-2 border border-black-border text-white-dim font-mono text-sm rounded hover:bg-white/5 transition-colors"
                    >
                      INSPECT
                    </button>
                  </div>
                </div>
              )}

              {state === 'executing' && (
                <div className="flex items-center gap-3 text-cyan font-mono">
                  <span className="animate-spin">◐</span>
                  <span>Executing on {incident.approval.affected.length} services...</span>
                </div>
              )}

              {state === 'resolved' && (
                <div className="flex items-center gap-3 text-green-500 font-mono">
                  <span>✓</span>
                  <span>RESOLVED - All services healthy</span>
                </div>
              )}

              {state === 'denied' && (
                <div className="flex items-center gap-3 text-red-500 font-mono">
                  <span>✗</span>
                  <span>DENIED - Agent awaiting further guidance</span>
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Queue */}
      <div className="border-x border-b border-black-border bg-black-light">
        <div className="px-4 py-2 border-b border-black-border">
          <span className="text-white-muted text-xs font-mono">QUEUE</span>
        </div>
        <div className="divide-y divide-black-border">
          {INCIDENTS.filter((_, i) => i !== currentIncidentIndex).slice(0, 2).map((inc) => (
            <div key={inc.id} className="flex items-center justify-between px-4 py-2 text-sm font-mono">
              <div className="flex items-center gap-2">
                <span className="text-white-muted">○</span>
                <span className="text-white">{inc.title}</span>
              </div>
              <span className="text-amber text-xs">[PENDING]</span>
            </div>
          ))}
          <div className="flex items-center justify-between px-4 py-2 text-sm font-mono">
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-white-dim">database backup completed</span>
            </div>
            <span className="text-white-muted text-xs">[2m ago]</span>
          </div>
        </div>
      </div>
    </div>
  )
}
